#!/usr/bin/env node
/*
 * @Author: mrlthf11
 * @LastEditors: mrlthf11
 * @Date: 2021-03-21 12:39:16
 * @LastEditTime: 2021-03-21 13:21:17
 * @Description: file content
 */

const { ESLint } = require("eslint");
const childProcess = require('child_process')

console.log('hook called');

function exec(command) {
  return new Promise((resolve, reject) => {
    childProcess.exec(command, resolve)
  })
}

(async function main() {
  await exec("git stash push -k")

  // 1. Create an instance.
  const eslint = new ESLint();

  // 2. Lint files.
  const results = await eslint.lintFiles(["./*.js"]);

  await exec("git stash pop")

  // 3. Format the results.
  const formatter = await eslint.loadFormatter("stylish");
  const resultText = formatter.format(results);

  // 4. Output it.
  console.log(resultText);
  const hasError = results.find((result) => result.errorCount)

  if (hasError) {
    process.exitCode = 1;
  }
})().catch((error) => {
  process.exitCode = 1;
  console.error(error);
});